### ISSUE TITLE
get_delta_roots seems to fail when there are no expired or new roots

### ISSUE THREAD

**Issue by jefferis** [seung-lab/PyChunkedGraph#394]
for these UTC/GMT times 
```
time_stamp_start="2022-02-03 11:48:10 GMT"
time_stamp_end="2022-02-03 11:49:10 GMT"
```

I see this from the call in caveclient
```
in py_call_impl(x, dots$args, dots$keywords) : 
  HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://prod.flywire-daf.com/segmentation/api/v1/table/fly_v31/delta_roots?timestamp_past=1643888890.0&timestamp_future=1643888950.0 content:b'{\n  "code": 500, \n  "duration": 1635.1826190948486, \n  "message": "need at least one array to concatenate", \n  "timestamp": "2022-02-03 12:14:14.772588", \n  "traceback": [\n    "Traceback (most recent call last):\\n", \n    "  File \\"/usr/local/lib/python3.7/site-packages/flask/app.py\\", line 1516, in full_dispatch_request\\n    rv = self.dispatch_request()\\n", \n    "  File \\"/usr/local/lib/python3.7/site-packages/flask/app.py\\", line 1502, in dispatch_request\\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\\n", \n    "  File \\"/usr/local/lib/python3.7/site-packages/middle_auth_client/decorators.py\\", line 254, in decorated_function\\n    return f(*args, **kwargs)\\n", \n    "  File \\"/usr/local/lib/python3.7/site-packages/middle_auth_client/decorators.py\\", line 361, in decorated_function\\n    return f(*args, **kwargs)\\n", \n    "  File \\"./pychunkedgraph/app/segmentation/v1/routes.py\\", line 513, in delta_roots\\n    resp = common.delta_roots(table_id)\\n", \n    "  File \\"./pychunkedgraph/app/segmentation/common.py\\", line 1232, in delta_roots\\n    old_roots, new_roots = cg.get_proofread_root_ids(timestamp_past, timestamp_future)\\n", \n    "  File \\"./pychunkedgraph/backend/chunkedgraph.py\\", line 4405, in get_proofread_root_ids\\n    [e[column_keys.OperationLogs.RootID] for e in log_entries.values()]\\n", \n    "  File \\"<__array_function__ internals>\\", line 6, in concatenate\\n", \n    "ValueError: need at least one array to concatenate\\n"\n  ]\n}\n'

Detailed traceback:
  File "/Users/jefferis/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/caveclient/chunkedgraph.py", line 818, in get_delta_roots
    r = handle_response(self.session.get(url, params=params))
  File "/Users/jefferis/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/caveclient/base.py", line 76, in handle_response
    _raise_for_status(response)
  File "/Users/jefferis/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/caveclient/base.py", line 68, in _raise_for_status
    raise requests.HTTPError(http_error_msg, response=r)
```

the `ValueError: need at least one array to concatenate` seems to occur if either category (expired or created) are empty.

**Comment by fcollman** [comment]
This is now fixed via #398 and #399
